openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: local-host
  url: http://localhost:8090/v1
security:
- {}
tags:
- description: not yet ready
  name: posts
paths:
  /posts:
    post:
      operationId: createposts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/posts'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts'
          description: successful operation
      summary: Creates the data
      tags:
      - posts
      x-eov-operation-handler: controllers/PostsController
  /posts/{postsId}:
    delete:
      operationId: deleteposts
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: postsId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - posts
      x-eov-operation-handler: controllers/PostsController
    get:
      operationId: getposts
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: postsId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts'
          description: successful operation
      summary: Get the element
      tags:
      - posts
      x-eov-operation-handler: controllers/PostsController
    put:
      operationId: updateposts
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: postsId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/posts'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts'
          description: successful operation
      summary: Updates the element
      tags:
      - posts
      x-eov-operation-handler: controllers/PostsController
  /posts/getAll:
    get:
      operationId: getAllposts
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/posts'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - posts
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/PostsController
components:
  schemas:
    posts:
      example:
        _id: _id
      properties:
        _id:
          type: string
      type: object
