openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: wabli-deploy-test
  url: https://83.212.100.226:4008/v1
security:
- {}
tags:
- description: not yet ready
  name: descs
paths:
  /descs:
    post:
      operationId: createdescs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/descs'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/descs'
          description: successful operation
      summary: Creates the data
      tags:
      - descs
      x-eov-operation-handler: controllers/DescsController
  /descs/{descsId}:
    delete:
      operationId: deletedescs
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: descsId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - descs
      x-eov-operation-handler: controllers/DescsController
    get:
      operationId: getdescs
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: descsId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/descs'
          description: successful operation
      summary: Get the element
      tags:
      - descs
      x-eov-operation-handler: controllers/DescsController
    put:
      operationId: updatedescs
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: descsId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/descs'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/descs'
          description: successful operation
      summary: Updates the element
      tags:
      - descs
      x-eov-operation-handler: controllers/DescsController
  /descs/getAll:
    get:
      operationId: getAlldescs
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/descs'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - descs
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/DescsController
components:
  schemas:
    descs:
      example:
        _id: _id
        desc: desc
      properties:
        _id:
          type: string
        desc:
          type: string
      required:
      - desc
      type: object
